class WS2812
  attr_reader brightness: Integer

  def initialize: (pin: Integer, num: Integer, ?order: Symbol) -> void
  def set_rgb: (Integer index, Integer r, Integer g, Integer b) -> void
  def set_hsb: (Integer index, Integer h, Integer s, Integer b) -> void
  def set_hex: (Integer index, Integer hex) -> void
  def fill: (Integer r, Integer g, Integer b) -> void
  def brightness=: (Integer val) -> Integer
  def show: () -> void
  def clear: () -> void
  def close: () -> void

  private

  def hsb_to_rgb: (Integer h, Integer s, Integer b) -> [Integer, Integer, Integer]
  def _init: (Integer pin) -> void
  def _show: (Array[Integer] buffer, Integer brightness, Integer color_order) -> void
  def _deinit: () -> void
end
